/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_FileAudioDeviceFactory */

#ifndef _Included_dev_onvoid_webrtc_FileAudioDeviceFactory
#define _Included_dev_onvoid_webrtc_FileAudioDeviceFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_onvoid_webrtc_FileAudioDeviceFactory
 * Method:    setFilesToUse
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_FileAudioDeviceFactory_setFilesToUse
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
